default_language_version:
  python: python3.10

repos:
  - repo: local

    hooks:
      - id: ruff
        name: Ruff
        entry: uv run ruff check
        language: system
        types: [ python ]
        args: [ "--fix", "--config=./config/.ruff.toml" ]
        exclude: ^tests/.*$

      - id: black
        name: Black
        entry: uv run black
        language: system
        types: [ python ]
        args: [ "--line-length", "120" ]

      - id: mypy
        name: Mypy
        entry: uv run mypy
        language: system
        types: [ python ]
        args: [ '--config-file', 'config/mypy.ini' ]

      - id: bandit
        name: Bandit
        entry: uv run bandit
        language: system
        types: [ python ]
        args: [ '--config', 'config/bandit.yml', '--severity-level', 'medium' ]
